repos:
    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.32.1
        hooks:
        -   id: pyupgrade
            args: [--py37-plus]

    -   repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
        -    id: isort
             additional_dependencies: ["colorama>=0.4.3"]
             args: ["--profile", "black"]

    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
        -   id: black
            args: [--skip-magic-trailing-comma]
